import {
  IconArrowRight,
  IconShieldFilled,
  IconGpsFilled,
  IconHelpHexagonFilled,
  IconLeafFilled,
  IconMicrophoneFilled,
  IconSatelliteFilled,
  IconSend2,
  IconProps as TablerIconProps,
  IconFlameFilled,
  IconPlayerPause,
  IconXFilled,
  IconPlayerPlayFilled,
  IconDatabasePlus,
  IconClock,
  IconCalendarPlus,
  IconChevronDown,
  IconCheck,
  IconCalendarEvent,
  IconArrowLeft,
  IconHomeFilled,
  IconInfoSquareRounded,
  IconDatabase,
  IconScript,
  IconMapPin,
  IconSearch,
  IconTrashXFilled,
  IconChartBar,
  IconDownload,
  IconCopy,
  IconWorld,
  IconExternalLink,
  IconMap2,
} from "@tabler/icons-react";
import { IconName } from "./IconName";
import { IconAxe, IconFist, IconGithub } from "./CustomIcons";

export const iconMap: Record<IconName, React.FC<TablerIconProps>> = {
  help: IconHelpHexagonFilled,
  mic: IconMicrophoneFilled,
  send: IconSend2,
  "arrow-right": IconArrowRight,
  satellite: IconSatelliteFilled,
  gps: IconGpsFilled,
  fist: IconFist,
  leaf: IconLeafFilled,
  shield: IconShieldFilled,
  flame: IconFlameFilled,
  axe: IconAxe,
  github: IconGithub,
  pause: IconPlayerPause,
  "data-plus": IconDatabasePlus,
  close: IconXFilled,
  play: IconPlayerPlayFilled,
  clock: IconClock,
  calendar: IconCalendarEvent,
  "calendar-plus": IconCalendarPlus,
  "chevron-down": IconChevronDown,
  check: IconCheck,
  "arrow-left": IconArrowLeft,
  farm: IconHomeFilled,
  info: IconInfoSquareRounded,
  data: IconDatabase,
  script: IconScript,
  "gps-pin": IconMapPin,
  search: IconSearch,
  trash: IconTrashXFilled,
  "bar-chart-2": IconChartBar,
  download: IconDownload,
  copy: IconCopy,
  world: IconWorld,
  "external-link": IconExternalLink,
  map: IconMap2,
};
